### ISSUE TITLE
Multiple broken dependencies in install script

### ISSUE THREAD

**Issue by jfolker** [RAPD/RAPD#108]
Installation of RAPD 2 fails early with at least 2 errors. The first error is a missing function in a python module, which I suspect is likely because the install scripts call python2 as "python", whereas present-day Ubuntu symlinks python to python3.

```
===== Running in modules: extracting files from clipper.gz

  removing .pyc files in /home/jfolker/RAPD/RAPD/share/cctbx/modules, walk? True
  removed 0 files
===== Running in .: base
Traceback (most recent call last):
  File "/home/jfolker/RAPD/RAPD/share/cctbx/modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 25, in <module>
    from package_defs import *
  File "/home/jfolker/RAPD/RAPD/share/cctbx/modules/cctbx_project/libtbx/auto_build/package_defs.py", line 135, in <module>
    distribution = platform.dist()
AttributeError: module 'platform' has no attribute 'dist'
Process failed with return code 1
Performing actions: hot update base build
Installing base packages using:
  python modules/cctbx_project/libtbx/auto_build/install_base_packages.py --python-shared --cctbx --cctbx --nproc=8 -v --skip-base=hdf5,lz4_plugin,py2app,wxpython,docutils,pyopengl,pillow,tiff,cairo,fonts,render,fontconfig,pixman,png,sphinx,freetype,gtk,matplotlib,cython,h5py,gettext,numpy,pythonextra,pytest,junitxml,libsvm,pyrtf,six,send2trash,jinja2,orderedset,procrunner,tabulate,scipy,scikit_learn,biopython,expat,glib,mrcfile --skip-if-exists
===== Downloading http://cci.lbl.gov/repositories/annlib.gz:  0.5 MB'

```

The second error may not be so easily fixed either: it seems we depend on remote repositories that no longer exist. I ran into this same problem yesterday, and it seems the repositories we need were either taken down from University of Cambridge or moved to a new location.

```
===== Running in modules: git clone --recursive https://git.csx.cam.ac.uk/cimr-phaser/phaser_regression.git phaser_regression --progress --verbose
Cloning into 'phaser_regression'...
fatal: unable to access 'https://git.csx.cam.ac.uk/cimr-phaser/phaser_regression.git/': Could not resolve host: git.csx.cam.ac.uk
===== Running in modules: git clone --recursive https://git.uis.cam.ac.uk/cimr-phaser/phaser.git phaser --progress --verbose
Cloning into 'phaser'...
fatal: unable to access 'https://git.uis.cam.ac.uk/cimr-phaser/phaser.git/': Could not resolve host: git.uis.cam.ac.uk

  removing .pyc files in /home/jfolker/RAPD/RAPD/share/cctbx/modules, walk? True
  removed 3 files
===== Running in .: base
Traceback (most recent call last):
  File "/home/jfolker/RAPD/RAPD/share/cctbx/modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 25, in <module>
    from package_defs import *
  File "/home/jfolker/RAPD/RAPD/share/cctbx/modules/cctbx_project/libtbx/auto_build/package_defs.py", line 135, in <module>
    distribution = platform.dist()
AttributeError: module 'platform' has no attribute 'dist'
Process failed with return code 1
Could not install cctbx
jfolker@office-b008:~/RAPD/RAPD/install$ 
```

**Comment by schuerjp1** [comment]
Hi Jory,

   We have a local branch of RAPD2 that I converted to Python3, but we have not tested it yet. It's current state requires a fair amount of computing resources to run because different modules are configured to run on separate machines. Once the ring does down, I am going to convert the modules to run as containers on the same machine, which should not be a problem on a modern server.

   As we talked outside today, the Phaser source code is now available with CCTBX from LBNL with a developer account. I believe it is also available with Phenix but that would not be available to companies.

Jon


--
Jonathan P. Schuermann, Ph. D.
Beamline Scientist and Computing Lead
NE-CAT/Cornell University
Argonne National Laboratory, 436E
9700 S. Cass Ave.
Lemont, IL 60439

Email: ***@***.***
Tel: (630) 252-0682


________________________________
From: Jory Folker ***@***.***>
Sent: Thursday, March 30, 2023 12:41 PM
To: RAPD/RAPD ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [RAPD/RAPD] Multiple broken dependencies in install script (Issue #108)


Installation of RAPD 2 fails early with at least 2 errors. The first error is a missing function in a python module, which I suspect is likely because the install scripts call python2 as "python", whereas present-day Ubuntu symlinks python to python3.

===== Running in modules: extracting files from clipper.gz

  removing .pyc files in /home/jfolker/RAPD/RAPD/share/cctbx/modules, walk? True
  removed 0 files
===== Running in .: base
Traceback (most recent call last):
  File "/home/jfolker/RAPD/RAPD/share/cctbx/modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 25, in <module>
    from package_defs import *
  File "/home/jfolker/RAPD/RAPD/share/cctbx/modules/cctbx_project/libtbx/auto_build/package_defs.py", line 135, in <module>
    distribution = platform.dist()
AttributeError: module 'platform' has no attribute 'dist'
Process failed with return code 1
Performing actions: hot update base build
Installing base packages using:
  python modules/cctbx_project/libtbx/auto_build/install_base_packages.py --python-shared --cctbx --cctbx --nproc=8 -v --skip-base=hdf5,lz4_plugin,py2app,wxpython,docutils,pyopengl,pillow,tiff,cairo,fonts,render,fontconfig,pixman,png,sphinx,freetype,gtk,matplotlib,cython,h5py,gettext,numpy,pythonextra,pytest,junitxml,libsvm,pyrtf,six,send2trash,jinja2,orderedset,procrunner,tabulate,scipy,scikit_learn,biopython,expat,glib,mrcfile --skip-if-exists
===== Downloading http://cci.lbl.gov/repositories/annlib.gz:  0.5 MB'



The second error may not be so easily fixed either: it seems we depend on remote repositories that no longer exist. I ran into this same problem yesterday, and it seems the repositories we need were either taken down from University of Cambridge or moved to a new location.

===== Running in modules: git clone --recursive https://git.csx.cam.ac.uk/cimr-phaser/phaser_regression.git phaser_regression --progress --verbose
Cloning into 'phaser_regression'...
fatal: unable to access 'https://git.csx.cam.ac.uk/cimr-phaser/phaser_regression.git/': Could not resolve host: git.csx.cam.ac.uk
===== Running in modules: git clone --recursive https://git.uis.cam.ac.uk/cimr-phaser/phaser.git phaser --progress --verbose
Cloning into 'phaser'...
fatal: unable to access 'https://git.uis.cam.ac.uk/cimr-phaser/phaser.git/': Could not resolve host: git.uis.cam.ac.uk

  removing .pyc files in /home/jfolker/RAPD/RAPD/share/cctbx/modules, walk? True
  removed 3 files
===== Running in .: base
Traceback (most recent call last):
  File "/home/jfolker/RAPD/RAPD/share/cctbx/modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 25, in <module>
    from package_defs import *
  File "/home/jfolker/RAPD/RAPD/share/cctbx/modules/cctbx_project/libtbx/auto_build/package_defs.py", line 135, in <module>
    distribution = platform.dist()
AttributeError: module 'platform' has no attribute 'dist'
Process failed with return code 1
Could not install cctbx
***@***.***:~/RAPD/RAPD/install$
