### ISSUE TITLE
Error in get_cif

### ISSUE THREAD

**Issue by frankvm04** [RAPD/RAPD#16]
There is an error if there is no cache directories. Should be trivial to fix...

`Process get_cif:
Traceback (most recent call last):
  File "/Users/fmurphy/workspace/rapd_github/share/cctbx/base/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Users/fmurphy/workspace/rapd_github/src/plugins/get_cif/plugin.py", line 124, in run
    self.process()
  File "/Users/fmurphy/workspace/rapd_github/src/plugins/get_cif/plugin.py", line 144, in process
    self.get_cif_files()
  File "/Users/fmurphy/workspace/rapd_github/src/plugins/get_cif/plugin.py", line 253, in get_cif_files
    with open(cached_file, "wb") as outfile:
IOError: [Errno 2] No such file or directory: '/tmp/rapd_cache/cif_files/1qrv.cif.gz'
`

**Comment by frankvm04** [comment]
Pull request has solution
