### ISSUE TITLE
Crash when defining detector on command line

### ISSUE THREAD

**Issue by frankvm04** [RAPD/RAPD#2]
Crashes when indexing with user-defined detector

rapd.index -d necat_adsc_q315 APS_NECAT_24-ID-C/data/thaum1_PAIR_0_0001.cbf

---------------------
RAPD Index & Strategy
---------------------

Data file(s)
  /Users/frankmurphy/workspace/rapd_github/test_data/APS_NECAT_24-ID-C/data/thaum1_PAIR_0_0001.cbf
Traceback (most recent call last):
  File "/Users/frankmurphy/workspace/rapd_github/src/plugins/index/commandline.py", line 503, in <module>
    main()
  File "/Users/frankmurphy/workspace/rapd_github/src/plugins/index/commandline.py", line 441, in main
    if site_module:
UnboundLocalError: local variable 'site_module' referenced before assignment

**Comment by frankvm04** [comment]
This was a really simple fix. Still not able to use a site when running from the CLI though...
