### ISSUE TITLE
rapd.integrate failure

### ISSUE THREAD

**Issue by jbrunzelle** [RAPD/RAPD#46]
rapd.integrate fails to integrate data collected on mar300 at ls-cat
here is the run info I will send data, and prior to the run I did do a git pull to make sure we had the latest version.
 rapd.integrate ../141_1_1_2.###

---------------
RAPD Intgration
---------------
analyze_data_sources ../141_1_1_2.###

Data to be integrated
  From /pf/esafs/edu/northwestern/k-brister/166421/f/test/insulin/141-2/141_1_1_2.001
    To /pf/esafs/edu/northwestern/k-brister/166421/f/test/insulin/141-2/141_1_1_2.060
Traceback (most recent call last):
  File "/pf/local/rapd/src/plugins/integrate/commandline.py", line 412, in <module>
    main()
  File "/pf/local/rapd/src/plugins/integrate/commandline.py", line 377, in main
    run_data = get_run_data(detector_module, image_0_data, image_n_data, commandline_args)
  File "/pf/local/rapd/src/plugins/integrate/commandline.py", line 141, in get_run_data
    image_0_data.get("run_number")),
  File "/pf/local/rapd/src/sites/detectors/lscat_rayonix_mx300.py", line 110, in create_image_template
    image_template = IMAGE_TEMPLATE % (image_prefix, run_number)
TypeError: not all arguments converted during string formatting

**Comment by schuerjp1** [comment]
fixed
