### ISSUE TITLE
Error "Could not install cctbx" on Centos6.7

### ISSUE THREAD

**Issue by zip2017** [RAPD/RAPD#48]
Hi Frank,

I was trying to install RAPD on my Desktop with Cenos6.7 but failed. Could you help me to fix it? The error messages are listed below. 

Best.
ZP
..........................................................................................................................................

Installing Python...
  log file is /home/zhipu/xtal_lzp/RAPD-master/share/cctbx/base_tmp/Python_install_log
  getting package Python-2.7.13.tgz...
    downloading from http://cci.lbl.gov/cctbx_dependencies : 16.3 MB
    [0%.........20%.........40%.........60%.........80%.........100%]
  installing Python-2.7.13.tgz...
Traceback (most recent call last):
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 1491, in <module>
    installer(args=sys.argv, log=sys.stdout)
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 217, in __init__
    self.build_dependencies(packages=packages)
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 683, in build_dependencies
    getattr(self, 'build_%s'%i)()
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 759, in build_python
    self.call('make install', log=log, cwd=python_dir)
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 307, in call
    return call(args, log=log, verbose=self.verbose, **kwargs)
  File "/home/zhipu/xtal_lzp/RAPD-master/share/cctbx/modules/cctbx_project/libtbx/auto_build/installer_utils.py", line 81, in call
    raise RuntimeError("Call to '%s' failed with exit code %d" % (args, rc))
RuntimeError: Call to 'make install' failed with exit code 2
Process failed with return code 1
Could not install cctbx

**Comment by frankvm04** [comment]
Hmmm... I will check this.

**Comment by frankvm04** [comment]
Sorry for the extreme delay. I have gotten past this point. It may be that the check for OS dependencies missed a requirement (`make` is my guess). I have updated install in the branch to work.

I should have a pull request to master soon.
