### ISSUE TITLE
rapd.index error during strategy calculations

### ISSUE THREAD

**Issue by jbrunzelle** [RAPD/RAPD#60]
Indexed two data frames and indexing completes but during the best part the process exits with an error
This error occurs for both the eiger 9M and mar300

Starting strategy calculations
Looking at /pf/esafs/org/vai/eric.xu/173090/d/Li_20711201_21d/screen/r/rapd_index_CS386A_1_1_1_S.002_CS386A_1_1_1_S.001/1/0/best.log
Process AutoindexingStrategy:
Traceback (most recent call last):
  File "/pf/local/rapd/share/cctbx/base/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/pf/local/rapd/src/plugins/index/plugin.py", line 447, in run
    self.run_queue()
  File "/pf/local/rapd/src/plugins/index/plugin.py", line 1505, in run_queue
    job1 = self.postprocess_best(log)
  File "/pf/local/rapd/src/plugins/index/plugin.py", line 1295, in postprocess_best
    log = open(inp, "r").readlines()
IOError: [Errno 2] No such file or directory: '/pf/esafs/org/vai/eric.xu/173090/d/Li_20711201_21d/screen/r/rapd_index_CS386A_1_1_1_S.002_CS386A_1_1_1_S.001/1/0/best.log'

[rapd_index.log.txt](https://github.com/RAPD/RAPD/files/1563190/rapd_index.log.txt)

**Comment by frankvm04** [comment]
Closed
