### ISSUE TITLE
rapd.integrate end error

### ISSUE THREAD

**Issue by jbrunzelle** [RAPD/RAPD#63]
got the following error during an integration run towards the end

Process FastIntegration:
Traceback (most recent call last):
  File "/pf/local/rapd/share/cctbx/base/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/pf/local/rapd/src/plugins/integrate/plugin.py", line 284, in run
    self.process()
  File "/pf/local/rapd/src/plugins/integrate/plugin.py", line 476, in process
    final_results = self.finish_data(full_integration_results)
  File "/pf/local/rapd/src/plugins/integrate/plugin.py", line 2057, in finish_data
    arch_prod_file, arch_prod_hash = archive.compress_file(prod_file)
  File "/pf/local/rapd/src/utils/archive.py", line 101, in compress_file
    with tarfile.open(archive_name, "w:bz2") as tar:
  File "/pf/local/rapd/share/cctbx/base/lib/python2.7/tarfile.py", line 1693, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/pf/local/rapd/share/cctbx/base/lib/python2.7/tarfile.py", line 1770, in bz2open
    raise CompressionError("bz2 module is not available")
CompressionError: bz2 module is not available

**Comment by frankvm04** [comment]
Probably have to add it to the install - checking.

**Comment by frankvm04** [comment]
Closed!
